# Generated by Django 5.0.4 on 2024-04-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergeno',
        ),
    ]
