# Generated by Django 5.0.4 on 2024-05-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_delete_alergeno'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
