# Generated by Django 5.0.2 on 2024-05-17 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingredientes', models.TextField()),
                ('tipo_ingredientes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.TextField()),
                ('status_pagamento', models.TextField()),
                ('data_de_transacao', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaHasIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='descricao',
            new_name='categoria_receita',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='modo_de_preparo',
            new_name='modo_preparo',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='id_receita',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='url_imagem_perfil',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='dica_receita',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_pessoas',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_audio_receita',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ingredientes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pagamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.pagamento'),
        ),
        migrations.AddField(
            model_name='receitahasingredientes',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
    ]
