# Generated by Django 5.0.2 on 2024-05-20 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingredientes', models.TextField(default='')),
                ('tipo_ingredientes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='LivroDeReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.TextField(default='')),
                ('status_pagamento', models.TextField(default='')),
                ('data_de_transacao', models.DateTimeField(default=None)),
                ('valor', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaHasIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='id_receita',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='modo_de_preparo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='dica_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_pessoas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_audio_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livrodereceitas',
            name='receitas',
            field=models.ManyToManyField(to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='livrodereceitas',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receitahasingredientes',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
    ]
