# Generated by Django 5.0.2 on 2024-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_receita_quantidade_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='url_audio_receita',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.BinaryField(default=b''),
        ),
    ]
