# Generated by Django 5.0.2 on 2024-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_receita_url_audio_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_audio_receita',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.TextField(default=''),
        ),
    ]
