# Generated by Django 5.0.2 on 2024-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_receita_quantidade_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_pessoas',
            field=models.TextField(default=''),
        ),
    ]
