# Generated by Django 5.0.2 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_receita_quantidade_horas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingredientes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('proteina', 'Proteína'), ('carboidrato', 'Carboidrato'), ('oleos_gorduras', 'Óleos/Gorduras'), ('carnes', 'Carnes'), ('vegetais', 'Vegetais'), ('frutas', 'Frutas'), ('legumes', 'Legumes')], max_length=20)),
                ('unidade_de_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='receitahasingredientes',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='receitahasingredientes',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='receita',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='categoria_receita',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='modo_preparo',
            new_name='modo_de_preparo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='url_imagem_perfil',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='dica_receita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='quantidade_horas',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='quantidade_pessoas',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='url_audio_receita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='url_imagem_receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receita',
            name='id_receita',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Favoritar',
        ),
        migrations.DeleteModel(
            name='Ingredientes',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='ReceitaHasIngredientes',
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
