# Generated by Django 5.0.2 on 2024-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_receita_quantidade_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='url_imagem_receita',
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_pessoas',
            field=models.TextField(default=''),
        ),
    ]
