# Generated by Django 5.0.2 on 2024-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_receita_url_imagem_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_audio_receita',
            field=models.URLField(default=''),
        ),
    ]
