# Generated by Django 5.0.2 on 2024-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_receita_url_imagem_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='quantidade_horas',
            field=models.IntegerField(default=None),
        ),
    ]
