# Generated by Django 5.0.2 on 2024-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_receita_quantidade_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='quantidade_horas',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='quantidade_pessoas',
        ),
    ]
