# Generated by Django 5.0.2 on 2024-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_receita_quantidade_horas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='url_audio_receita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='url_imagem_receita',
        ),
    ]
