# Generated by Django 5.0.2 on 2024-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_receita_url_audio_receita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='dica_receita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='modo_preparo',
        ),
    ]
