# Generated by Django 5.0.2 on 2024-05-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_receita_dica_receita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria_receita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='nome_receita',
        ),
    ]
