# Generated by Django 5.0.2 on 2024-05-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_receita_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='nome_ingredientes',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='tipo_ingredientes',
        ),
    ]
