# Generated by Django 5.0.2 on 2024-05-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_ingredientes_nome_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_de_transacao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='status_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor',
        ),
    ]
