# Generated by Django 5.0.2 on 2024-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_remove_pagamento_data_de_transacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='receita',
        ),
    ]
