# Generated by Django 5.0.2 on 2024-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_receitahasingredientes_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritar',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='favoritar',
            name='usuario',
        ),
    ]
