# Generated by Django 5.0.2 on 2024-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_remove_favoritar_receita_remove_favoritar_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='receita',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='url_imagem_perfil',
        ),
    ]
