# Generated by Django 5.0.2 on 2024-05-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_remove_customuser_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ingredientes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pagamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.pagamento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receita',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='url_imagem_perfil',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='favoritar',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='nome_ingredientes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='tipo_ingredientes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_de_transacao',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status_pagamento',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='dica_receita',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='nome_receita',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_horas',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade_pessoas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_audio_receita',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='receitahasingredientes',
            name='ingredientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes'),
        ),
        migrations.AddField(
            model_name='receitahasingredientes',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='ingredientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingredientes'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
