# Generated by Django 5.0.2 on 2024-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_customuser_comentario_customuser_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='dica_receita',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='quantidade_horas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_audio_receita',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='url_imagem_receita',
            field=models.TextField(default=''),
        ),
    ]
