from django.urls import path
from.import views


urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login_view, name='login'),
    path('loginerror/', views.login_error, name='loginerror'),
    path('esqueciSenha/', views.esqueciSenha, name='esqueci-senha'),
    path('alterarSenha/<int:cod>/', views.alterarSenha, name='alterar-senha'),
    path('verificaoSenha/', views.verificacao, name='verificacao-senha'),
    path('plataforma/', views.plataforma, name='PlataForma'),
    path('receitaAprendiz/', views.receitaAprendiz, name='receitaAprendiz'),
    path('receitaSubChef/', views.receitaSubChef, name='receitaSubChef'),
    path('receitaMiniChef/', views.receitaMiniChef, name='receitaMiniChef'),
    path('receitaConfeiteiro/', views.receitaConfeiteiro, name='receitaConfeiteiro'),
    path('receitaChef/', views.receitaChef, name='receitaChef'),
    path('receitaVegano/', views.receitaVegano, name='receitaVegano'),
    path('buscaReceitaAprendiz/', views.buscaReceitaAprendiz, name='buscaReceitaAprendiz'),
    path('buscaReceitaAprendiz/', views.buscaReceitaAprendiz, name='buscaReceitaAprendiz'),
    path('buscaReceitaMiniChef/', views.buscaReceitaMiniChef, name='buscaReceitaMiniChef'),
    path('buscaReceitaSubChef/', views.buscaReceitaSubChef, name='buscaReceitaSubChef'),
    path('buscaReceitaChef/', views.buscaReceitaChef, name='buscaReceitaChef'),
    path('buscaReceitaConfeiteiro/', views.buscaReceitaConfeiteiro, name='buscaReceitaConfeiteiro'),
    path('buscaReceitaVegano/', views.buscaReceitaVegano, name='buscaReceitaVegano'),
    path('homeAprendiz/', views.homeAprendiz, name='homeAprendiz'),
    path('homeMiniChef/', views.homeMiniChef, name='homeMiniChef'),
    path('homeSubChef/', views.homeSubChef, name='homeSubChef'),
    path('homeChef/', views.homeChef, name='homeChef'),
    path('homeConfeiteiro/', views.homeConfeiteiro, name='homeConfeiteiro'),
    path('homeVegano/', views.homeVegano, name='homeVegano'),
    path('livroReceitaAprendiz/', views.livroReceitaAprendiz, name='livroReceitaAprendiz'),
    path('livroReceitaMiniChef/', views.livroReceitaMiniChef, name='livroReceitaMiniChef'),
    path('livroReceitaSubChef/', views.livroReceitaSubChef, name='livroReceitaSubChef'),
    path('livroReceitaChef/', views.livroReceitaChef, name='livroReceitaChef'),
    path('livroReceitaConfeiteiro/', views.livroReceitaConfeiteiro, name='livroReceitaConfeiteiro'),
    path('livroReceitaVegano/', views.livroReceitaVegano, name='livroReceitaVegano'),
    path('minhasReceitasAprendiz/', views.minhasReceitasAprendiz, name='minhasReceitasAprendiz'),
    path('minhasReceitasMiniChef/', views.minhasReceitasMiniChef, name='minhasReceitasMiniChef'),
    path('minhasReceitasSubChef/', views.minhasReceitasSubChef, name='minhasReceitasSubChef'),
    path('minhasReceitasChef/', views.minhasReceitasChef, name='minhasReceitasChef'),
    path('minhasReceitasConfeiteiro/', views.minhasReceitasConfeiteiro, name='minhasReceitasConfeiteiro'),
    path('minhasReceitasVegano/', views.minhasReceitasVegano, name='minhasReceitasVegano'),
    path('adicionarReceitaAprendiz/', views.adicionarReceitaAprendiz, name='adicionarReceitaAprendiz'),
    path('adicionarReceitaMiniChef/', views.adicionarReceitaMiniChef, name='adicionarReceitaMiniChef'),
    path('adicionarReceitaSubChef/', views.adicionarReceitaSubChef, name='adicionarReceitaSubChef'),
    path('adicionarReceitaChef/', views.adicionarReceitaChef, name='adicionarReceitaChef'),
    path('adicionarReceitaConfeiteiro/', views.adicionarReceitaConfeiteiro, name='adicionarReceitaConfeiteiro'),
    path('adicionarReceitaVegano/', views.adicionarReceitaVegano, name='adicionarReceitaVegano'),
    path('editarPerfilAprendiz/', views.editarPerfilAprendiz, name='editarPerfilAprendiz'),
    path('editarPerfilMiniChef/', views.editarPerfilMiniChef, name='editarPerfilMiniChef'),
    path('editarPerfilSubChef/', views.editarPerfilSubChef, name='editarPerfilSubChef'),
    path('editarPerfilChef/', views.editarPerfilChef, name='editarPerfilChef'),
    path('editarPerfilConfeiteiro/', views.editarPerfilConfeiteiro, name='editarPerfilConfeiteiro'),
    path('editarPerfilVegano/', views.editarPerfilVegano, name='editarPerfilVegano'),
    path('logout/', views.logout_view, name='logout'),

        # Assinatura
    path('assinaturaAprendiz/', views.assinaturaAprendiz, name='assinatura-aprendiz'),
    path('assinaturaAprendizInfo1/', views.assinaturaAprendizInfor1, name='assinatura-aprendiz-info1'),
    path('assinaturaAprendizInfo2/', views.assinaturaAprendizInfor2, name='assinatura-aprendiz-info2'),
    path('assinaturaAprendizFinalizada/', views.assinaturaAprendizFinalizada, name='assinatura-aprendiz-finalizada'),

    path('assinaturaMiniChef/', views.assinaturaMiniChef, name='assinatura-mini-chef'),
    path('assinaturaMiniChefInfo1/', views.assinaturaMiniChefInfor1, name='assinatura-mini-chef-info1'),
    path('assinaturaMiniChefInfo2/', views.assinaturaMiniChefInfor2, name='assinatura-mini-chef-info2'),
    path('assinaturaMiniChefFinalizada/', views.assinaturaMiniChefFinalizada, name='assinatura-mini-chef-finalizada'),

    path('assinaturaSubChef/', views.assinaturaSubChef, name='assinatura-sub-chef'),
    path('assinaturaSubChefInfo1/', views.assinaturaSubChefInfor1, name='assinatura-sub-chef-info1'),
    path('assinaturaSubChefInfo2/', views.assinaturaSubChefInfor2, name='assinatura-sub-chef-info2'),
    path('assinaturaSubChefFinalizada/', views.assinaturaSubChefFinalizada, name='assinatura-sub-chef-finalizada'),

    path('assinaturaChef/', views.assinaturaChef, name='assinatura-chef'),
    path('assinaturaChefInfo1/', views.assinaturaChefInfor1, name='assinatura-chef-info1'),
    path('assinaturaChefInfo2/', views.assinaturaChefInfor2, name='assinatura-chef-info2'),
    path('assinaturaChefFinalizada/', views.assinaturaChefFinalizada, name='assinatura-chef-finalizada'),

    path('assinaturaConfeiteiro/', views.assinaturaConfeiteiro, name='assinatura-confeiteiro'),
    path('assinaturaConfeiteiroInfo1/', views.assinaturaConfeiteiroInfor1, name='assinatura-confeiteiro-info1'),
    path('assinaturaConfeiteiroInfo2/', views.assinaturaConfeiteiroInfor2, name='assinatura-confeiteiro-info2'),
    path('assinaturaConfeiteiroFinalizada/', views.assinaturaConfeiteiroFinalizada, name='assinatura-confeiteiro-finalizada'),

    path('assinaturaVegano/', views.assinaturaVegano, name='assinatura-vegano'),
    path('assinaturaVeganoInfo1/', views.assinaturaVeganoInfor1, name='assinatura-vegano-info1'),
    path('assinaturaVeganoInfo2/', views.assinaturaVeganoInfor2, name='assinatura-vegano-info2'),
    path('assinaturaVeganoFinalizada/', views.assinaturaVeganoFinalizada, name='assinatura-vegano-finalizada'),


    # Perfil -> Alterar Senha
    path('alterarSenha/', views.alterarSenha, name='alterar-senha'),
    path('novaSenha/', views.novaSenha, name='nova-senha'),
]